title: seongmin.
description: Where excess falls away, essence remains.
baseurl: ""
url: "https://takeachangs.github.io"

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - README.md
  - CLAUDE.md
  - .gitignore